### ISSUE TITLE
do not found iois  zipfile ,when I use the import.py program

### ISSUE THREAD

**Issue by MacTin** [anted/ioi_box#1]
this is my output
E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master>importer  contests/ioi2017_day1.py
INFO:__main__:Importing contest contests/ioi2017_day1.py
INFO:__main__:Downloading https://informatika.fer.hr/ioi_box/ioi2017_day1.zip to E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master\cache\ioi2017_day1.zip.
Traceback (most recent call last):
  File "E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master\importer.py", line 106, in <module>
    main()
  File "E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master\importer.py", line 102, in main
    ZipImporter().import_contest(module.Config)
  File "E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master\importer.py", line 86, in import_contest
    Downloader.download(config.ZIP_URL, destination, config.ZIP_SHA1)
  File "E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master\importer.py", line 61, in download
    if subprocess.call([Downloader.WGET, '-c', '-O',destination, url]):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

E:\Escuela\omi\omi\cms\ioi_box-master\ioi_box-master>importer  contests/ioi2017_day1.py

**Comment by anted** [comment]
@MacTin 

ioi_box is not supported on Windows :(. It should be possible to make it work but I don't have the resources to create official instructions. Should be easy to get it to run inside an Ubuntu virtual machine.

Additionally the error seems to be caused by missing "wget" utility rather than the file on the backend server.
